# Generated by Django 4.1.1 on 2022-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalname', models.CharField(max_length=100)),
                ('professionalsurname', models.CharField(max_length=100)),
                ('professionalprofesion', models.CharField(max_length=100)),
                ('professionalemail', models.EmailField(max_length=254)),
                ('professionalcellnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxexpirationdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxname', models.CharField(max_length=100)),
                ('taxdate', models.DateField()),
                ('taxresponsible', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Updatedinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalname', models.CharField(max_length=100)),
                ('informationdate', models.DateField()),
                ('informationtext', models.CharField(max_length=500)),
            ],
        ),
    ]
