# Generated by Django 4.1.1 on 2022-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloggername', models.CharField(max_length=100)),
                ('bloggersurname', models.CharField(max_length=100)),
                ('bloggerprofesion', models.CharField(max_length=100)),
                ('bloggeremail', models.EmailField(max_length=254)),
                ('bloggercellnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxexpirationdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxname', models.CharField(max_length=100)),
                ('taxdate', models.DateField()),
                ('taxresponsible', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Updatedinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloggername', models.CharField(max_length=100)),
                ('informationdate', models.DateField()),
                ('informationtext', models.CharField(max_length=500)),
            ],
        ),
    ]
