# Generated by Django 4.1.1 on 2022-10-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinformation',
            name='informationservice',
            field=models.CharField(default='Impuestos', max_length=100),
            preserve_default=False,
        ),
    ]
