# Generated by Django 4.1.1 on 2022-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinformation',
            name='informationtitle',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updatedinformation',
            name='informationtext',
            field=models.CharField(max_length=1000),
        ),
    ]
