# Generated by Django 4.1.1 on 2022-10-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0004_updatedinformation_informationtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinformation',
            name='informationtext',
            field=models.CharField(max_length=1500),
        ),
        migrations.CreateModel(
            name='AboutMeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutmeimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
