# Generated by Django 4.1.1 on 2022-10-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_updatedinformation_informationtext_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmeimage',
            old_name='image',
            new_name='imageabout',
        ),
        migrations.RemoveField(
            model_name='aboutmeimage',
            name='user',
        ),
    ]
