# Generated by Django 4.1.1 on 2022-10-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_rename_image_aboutmeimage_imageabout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionals',
            name='professionalimage',
            field=models.ImageField(blank=True, null=True, upload_to='professionalsimage'),
        ),
    ]
